version: 0.2
env:
  secrets-manager:
    DOCKER_HUB_USER: arn:aws:secretsmanager:ap-northeast-1:630481373697:secret:DockerHubCredential-f2dYUM:DOCKER_HUB_USER
    DOCKER_HUB_PASSWORD: arn:aws:secretsmanager:ap-northeast-1:630481373697:secret:DockerHubCredential-f2dYUM:DOCKER_HUB_PASSWORD

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USER --password-stdin
      - sh gradlew assemble
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$VERSION.$CODEBUILD_BUILD_NUMBER .
      - docker tag $IMAGE_REPO_NAME:$VERSION.$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$VERSION.$CODEBUILD_BUILD_NUMBER
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$VERSION.$CODEBUILD_BUILD_NUMBER